<?xml version="1.0" encoding="utf-8"?><Database Name="tanhoa" Class="DMADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.9;Initial Catalog=tanhoa;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="tanhoaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.g_ThongTinDHT" Member="g_ThongTinDHTs">
    <Type Name="g_ThongTinDHT">
      <Column Name="STT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaDMA" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ViTri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRV" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CoDHN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Hieu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PinNguon" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThietBi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HamDHT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TuCelloMK4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StatusDHT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TinhTrangBlogger" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TinhTrangPRV" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoSIM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoSeri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoGon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChannelId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChannelOut" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChannelCMP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StatusCMP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Img" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.g_GhiChu" Member="g_GhiChus">
    <Type Name="g_GhiChu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDMA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NOIDUNG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Users" Member="t_Users">
    <Type Name="t_User">
      <Column Name="Username" Type="System.String" DbType="NVarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Salt" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ConsumerId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoginTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>